development:
  adapter: postgresql
  database: aura_site_development

test: &test
  adapter: postgresql
  database: aura_site_test

production:
  adapter: postgresql
  database: aura_site

cucumber:
  <<: *test
